version: '3.8'

services:

  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${DB_PATH_HOST}:/var/lib/postgresql/data

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 80:8080